// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp-68YA7QX76xjpM79rRHNS1gfHhqTreE',
    appId: '1:51443739236:web:e6567f39c1df667cf20d71',
    messagingSenderId: '51443739236',
    projectId: 'netspend-dea37',
    authDomain: 'netspend-dea37.firebaseapp.com',
    databaseURL: 'https://netspend-dea37-default-rtdb.firebaseio.com',
    storageBucket: 'netspend-dea37.appspot.com',
    measurementId: 'G-Y5EKJDDK4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAzvYqbQvobi2T0iMtbRO0-5nviFPRhL0',
    appId: '1:51443739236:android:d454c0117d0f2892f20d71',
    messagingSenderId: '51443739236',
    projectId: 'netspend-dea37',
    databaseURL: 'https://netspend-dea37-default-rtdb.firebaseio.com',
    storageBucket: 'netspend-dea37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhZyNNzASG_-ISWvLJMwRXerGtuc9tu9A',
    appId: '1:51443739236:ios:ba85bd13f6e2e923f20d71',
    messagingSenderId: '51443739236',
    projectId: 'netspend-dea37',
    databaseURL: 'https://netspend-dea37-default-rtdb.firebaseio.com',
    storageBucket: 'netspend-dea37.appspot.com',
    iosClientId: '51443739236-ve6635rk72a7mljodqag29vkalf389tp.apps.googleusercontent.com',
    iosBundleId: 'com.enkasa.netspend',
  );
}
